apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: orsx1zo5q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: orsx1zo5q-go 
  name: orsx1zo5q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: orsx1zo5q-go 
