apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: orsx1zo5q-go 
  janus-idp.io/tekton: orsx1zo5q-go
  backstage.io/kubernetes-id: orsx1zo5q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: orsx1zo5q-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml